from typing import List, Optional, Iterator
from langsmith import traceable
from mcp.agents.base import BaseMedicalAgent
from mcp.agents.config import REVIEWER_MODEL, get_llm_cfg
import mcp.agents.tools.reviewer_tools # Ensure registration

class ReviewerAgent(BaseMedicalAgent):
    """
    ReviewerAgent is responsible for auditing the knowledge generated by LearningAgent.
    It ensures format compliance and internal logical consistency.
    """
    def __init__(self, llm_cfg: Optional[dict] = None, name: str = 'Reviewer Agent'):
        llm_cfg = llm_cfg or get_llm_cfg(REVIEWER_MODEL)
        
        system_prompt = (
            "你是一个极其严谨的医疗文档合规性审查员。你的职责是审计由其他 Agent 生成的医疗知识库。\n\n"
            "### 【审计任务】\n"
            "1. **格式校验**：调用 `verify_skill_format` 检查每一个新生成或更新的资源文件. 确保其包含：风险等级、下一步建议、是否建议联系团队、参考依据。任何缺失参考依据的知识条目必须被移除。\n"
            "2. **消歧处理**：调用 `resolve_skill_conflicts` 检查整个 `chemotherapy-side-effect-triage` 技能库，识别并修复任何判定标准或建议上的内部冲突。\n\n"
            "### 【工作原则】\n"
            "- **宁缺毋滥**：宁可移除不合规的知识，也不允许任何缺乏依据或格式错误的信息留在库中。\n"
            "- **自洽优先**：整个字典库必须保持逻辑上的绝对统一。\n\n"
            "### 【工具调用协议】\n"
            "如果你需要调用工具，你**必须**严格遵循以下 XML 格式：\n"
            "<tool_call>\n"
            "{\"name\": \"工具名称\", \"arguments\": {\"参数1\": \"值1\"}}\n"
            "</tool_call>\n"
            "严禁在 JSON 块中使用任何多余的空格或换行符，且 JSON 必须是标准的单行格式。"
        )
        
        tools = [
            'verify_skill_format',
            'resolve_skill_conflicts'
        ]
        
        super().__init__(
            llm_cfg=llm_cfg,
            name=name,
            system_prompt=system_prompt,
            tools=tools
        )

    @traceable(name="ReviewerAgent Run")
    def run(self, messages: List[dict]) -> Iterator[dict]:
        """
        Standard run method.
        """
        for chunk in self.agent.run(messages):
            yield chunk

    @traceable(name="ReviewerAgent Audit")
    def audit(self, skill_name: str, resource_names: List[str]) -> str:
        """
        Runs the audit process for a specific skill.
        """
        resources_str = ", ".join(resource_names)
        prompt = (
            f"请对技能 `{skill_name}` 进行全面审计。\n"
            f"1. 针对以下受影响的资源文件执行格式校验：{resources_str}。\n"
            f"2. 对整个技能库执行内部消歧检查。\n"
            "处理完成后请报告审计结果。"
        )
        return self.chat(prompt)
